from dataclasses import dataclass
from typing import Dict, List, Optional

from app.domains.recommendation.domain.value_object.place_type import PlaceType
from app.domains.recommendation.service.place_search_query_builder import ActivityKind

CURATED_SCORE = 0.9


@dataclass(frozen=True)
class CuratedPlaceConfig:
    search_query: str
    place_type: PlaceType
    activity_kind: Optional[ActivityKind] = None
    latitude: Optional[float] = None
    longitude: Optional[float] = None


_SEONGSU_PLACES: List[CuratedPlaceConfig] = [
    # 레스토랑
    CuratedPlaceConfig("죠죠 성수", PlaceType.RESTAURANT),
    CuratedPlaceConfig("HDD피자 성수", PlaceType.RESTAURANT),
    CuratedPlaceConfig("진작다이닝 성수", PlaceType.RESTAURANT),
    CuratedPlaceConfig("동구식당 성수", PlaceType.RESTAURANT),
    CuratedPlaceConfig("투파인드피터 서울성수점", PlaceType.RESTAURANT),
    CuratedPlaceConfig("바오 서울 성수", PlaceType.RESTAURANT),
    CuratedPlaceConfig("고우 성수", PlaceType.RESTAURANT),
    CuratedPlaceConfig("이가네양꼬치 성수직영점", PlaceType.RESTAURANT),
    CuratedPlaceConfig("규카츠정 성수점", PlaceType.RESTAURANT),
    CuratedPlaceConfig("텐동식당 성수", PlaceType.RESTAURANT),
    CuratedPlaceConfig("탐광 성수", PlaceType.RESTAURANT),
    CuratedPlaceConfig("솔솥 성수점", PlaceType.RESTAURANT),
    CuratedPlaceConfig("시옹마오 성수", PlaceType.RESTAURANT),
    CuratedPlaceConfig("태양곱창 성수", PlaceType.RESTAURANT),
    CuratedPlaceConfig("키키노히호 성수점", PlaceType.RESTAURANT),
    CuratedPlaceConfig("벱 성수", PlaceType.RESTAURANT),
    CuratedPlaceConfig("소문난성수감자탕", PlaceType.RESTAURANT),
    CuratedPlaceConfig("능동미나리 성수점", PlaceType.RESTAURANT),
    CuratedPlaceConfig("도도한면 성수본점", PlaceType.RESTAURANT),
    CuratedPlaceConfig("오카츠 성수본점", PlaceType.RESTAURANT),
    CuratedPlaceConfig("멘노아지 성수", PlaceType.RESTAURANT),
    CuratedPlaceConfig("롸카두들 내시빌 핫치킨 성수점", PlaceType.RESTAURANT),
    CuratedPlaceConfig("르프리크 성수", PlaceType.RESTAURANT),
    CuratedPlaceConfig("피읻짜 성수", PlaceType.RESTAURANT),
    CuratedPlaceConfig("마리오네 성수", PlaceType.RESTAURANT),
    CuratedPlaceConfig("이짜 성수", PlaceType.RESTAURANT),
    CuratedPlaceConfig("파작 북성수점", PlaceType.RESTAURANT),
    CuratedPlaceConfig("세스크멘슬 본점", PlaceType.RESTAURANT),
    CuratedPlaceConfig("플라토 성수", PlaceType.RESTAURANT),
    CuratedPlaceConfig("피리어드 성수", PlaceType.RESTAURANT),
    CuratedPlaceConfig("타크 서울숲", PlaceType.RESTAURANT),
    CuratedPlaceConfig("컴오프 성수", PlaceType.RESTAURANT),
    CuratedPlaceConfig("시즈니 성수", PlaceType.RESTAURANT),
    CuratedPlaceConfig("프롤라 성수", PlaceType.RESTAURANT),
    CuratedPlaceConfig("피자슬라이스 서울 성수", PlaceType.RESTAURANT),
    CuratedPlaceConfig("서울숲누룽지통닭구이", PlaceType.RESTAURANT),
    # 카페
    CuratedPlaceConfig("사이드템포 성수", PlaceType.CAFE),
    CuratedPlaceConfig("언라인 성수", PlaceType.CAFE),
    CuratedPlaceConfig("따우전드 성수", PlaceType.CAFE),
    CuratedPlaceConfig("맥코이 성수", PlaceType.CAFE),
    CuratedPlaceConfig("본지르르 성수", PlaceType.CAFE),
    CuratedPlaceConfig("로우키 성수", PlaceType.CAFE),
    CuratedPlaceConfig("아가젤라또 성수", PlaceType.CAFE),
    CuratedPlaceConfig("커피냅로스터스 성수", PlaceType.CAFE),
    CuratedPlaceConfig("소파 성수", PlaceType.CAFE),
    CuratedPlaceConfig("마를리 성수", PlaceType.CAFE),
    CuratedPlaceConfig("업사이드 성수", PlaceType.CAFE),
    CuratedPlaceConfig("로우커피스탠드 성수", PlaceType.CAFE),
    CuratedPlaceConfig("어니언 성수", PlaceType.CAFE),
    CuratedPlaceConfig("와이덴 성수", PlaceType.CAFE),
    CuratedPlaceConfig("리사르커피 성수점", PlaceType.CAFE),
    CuratedPlaceConfig("피어커피 성수", PlaceType.CAFE),
    CuratedPlaceConfig("피카워크샵 성수", PlaceType.CAFE),
    CuratedPlaceConfig("포어플랜 성수", PlaceType.CAFE),
    CuratedPlaceConfig("플디 성수", PlaceType.CAFE),
    CuratedPlaceConfig("로우키커피 헤이그라운드점", PlaceType.CAFE),
    CuratedPlaceConfig("블루보틀 성수", PlaceType.CAFE),
    CuratedPlaceConfig("리커버리커피바 성수", PlaceType.CAFE),
    CuratedPlaceConfig("챔프커피 성수", PlaceType.CAFE),
    CuratedPlaceConfig("베티버 성수", PlaceType.CAFE),
    CuratedPlaceConfig("토마스베이커리 성수", PlaceType.CAFE),
    CuratedPlaceConfig("카멜 성수점", PlaceType.CAFE),
    CuratedPlaceConfig("하우스오브바이닐 성수점", PlaceType.CAFE),
    CuratedPlaceConfig("심퍼티쿠시 성수점", PlaceType.CAFE),
    CuratedPlaceConfig("식당 오츠 성수", PlaceType.CAFE),
    CuratedPlaceConfig("타코스퀘어 성수", PlaceType.CAFE),
    CuratedPlaceConfig("제스티살룬 성수", PlaceType.CAFE),
    CuratedPlaceConfig("도우또 성수", PlaceType.CAFE),
    CuratedPlaceConfig("미쁘동 서울숲", PlaceType.CAFE),
    CuratedPlaceConfig("요시 성수", PlaceType.CAFE),
    CuratedPlaceConfig("핫쵸 성수점", PlaceType.CAFE, latitude=37.546853, longitude=127.044135),
    CuratedPlaceConfig("5 to 7 성수", PlaceType.CAFE),
    CuratedPlaceConfig("도토리 오븐 성수", PlaceType.CAFE),
    CuratedPlaceConfig("더커피 성수", PlaceType.CAFE),
    CuratedPlaceConfig("마일스톤커피 성수", PlaceType.CAFE),
    CuratedPlaceConfig("컴오프로스터스 성수", PlaceType.CAFE),
    # Activity - 체험 (WORKSHOP)
    CuratedPlaceConfig("모나미 스토어 성수점", PlaceType.ACTIVITY, ActivityKind.WORKSHOP),
    CuratedPlaceConfig("포인트오브뷰 성수", PlaceType.ACTIVITY, ActivityKind.WORKSHOP),
    CuratedPlaceConfig("데이지크 성수", PlaceType.ACTIVITY, ActivityKind.WORKSHOP),
    CuratedPlaceConfig("탬버린즈 성수", PlaceType.ACTIVITY, ActivityKind.WORKSHOP),
    # Activity - 전시/문화 (EXHIBITION)
    CuratedPlaceConfig("LCDC Seoul", PlaceType.ACTIVITY, ActivityKind.EXHIBITION),
    CuratedPlaceConfig("성수연방", PlaceType.ACTIVITY, ActivityKind.EXHIBITION),
    # Activity - 쇼핑 (SHOPPING)
    CuratedPlaceConfig("카키스 성수", PlaceType.ACTIVITY, ActivityKind.SHOPPING),
    CuratedPlaceConfig("EQL 성수", PlaceType.ACTIVITY, ActivityKind.SHOPPING),
    CuratedPlaceConfig("카시나 성수", PlaceType.ACTIVITY, ActivityKind.SHOPPING),
    CuratedPlaceConfig("젠틀몬스터 성수", PlaceType.ACTIVITY, ActivityKind.SHOPPING),
    CuratedPlaceConfig("비이커 성수 플래그십스토어", PlaceType.ACTIVITY, ActivityKind.SHOPPING),
    CuratedPlaceConfig("키스 서울 성수", PlaceType.ACTIVITY, ActivityKind.SHOPPING),
    # Activity - 산책 (WALK)
    CuratedPlaceConfig("서울숲", PlaceType.ACTIVITY, ActivityKind.WALK),
    # Activity - 칵테일바/와인바/이자카야 (BAR, NIGHTLIFE)
    CuratedPlaceConfig("페어드 칵테일 성수", PlaceType.ACTIVITY, ActivityKind.BAR),
    CuratedPlaceConfig("리타르단도 성수", PlaceType.ACTIVITY, ActivityKind.BAR),
    CuratedPlaceConfig("포도젝트 성수", PlaceType.ACTIVITY, ActivityKind.BAR),
    CuratedPlaceConfig("기러기둥지 성수", PlaceType.ACTIVITY, ActivityKind.BAR),
    CuratedPlaceConfig("목탄 성수", PlaceType.ACTIVITY, ActivityKind.BAR),
    CuratedPlaceConfig("토메루 성수점", PlaceType.ACTIVITY, ActivityKind.BAR),
    CuratedPlaceConfig("야키토리나루토 성수", PlaceType.ACTIVITY, ActivityKind.BAR),
    CuratedPlaceConfig("진도켄 성수점", PlaceType.ACTIVITY, ActivityKind.BAR),
    CuratedPlaceConfig("브루어리을를 서울숲", PlaceType.ACTIVITY, ActivityKind.BAR),
    CuratedPlaceConfig("우드파이어 파로 성수", PlaceType.ACTIVITY, ActivityKind.BAR, latitude=37.538525, longitude=127.056572),
]

_HANNAM_PLACES: List[CuratedPlaceConfig] = [
    # 레스토랑
    CuratedPlaceConfig("교카이젠 한남", PlaceType.RESTAURANT),
    CuratedPlaceConfig("한남동감자탕 본점", PlaceType.RESTAURANT),
    CuratedPlaceConfig("한남동한방통닭", PlaceType.RESTAURANT),
    CuratedPlaceConfig("소소막창 한남", PlaceType.RESTAURANT),
    CuratedPlaceConfig("부자피자 1호점", PlaceType.RESTAURANT),
    CuratedPlaceConfig("빠르크 한남점", PlaceType.RESTAURANT),
    CuratedPlaceConfig("벱 한남점", PlaceType.RESTAURANT),
    CuratedPlaceConfig("벽돌해피푸드 한남", PlaceType.RESTAURANT),
    CuratedPlaceConfig("뉴오더클럽 한남", PlaceType.RESTAURANT),
    CuratedPlaceConfig("다운타우너 한남", PlaceType.RESTAURANT),
    CuratedPlaceConfig("공기 한남", PlaceType.RESTAURANT),
    CuratedPlaceConfig("파이프그라운드 한남", PlaceType.RESTAURANT),
    CuratedPlaceConfig("윤세영식당 한남", PlaceType.RESTAURANT),
    CuratedPlaceConfig("오아시스 한남 브런치", PlaceType.RESTAURANT),
    CuratedPlaceConfig("타크 한남", PlaceType.RESTAURANT),
    # 카페
    CuratedPlaceConfig("아키비스트 한남점", PlaceType.CAFE),
    CuratedPlaceConfig("맥코이 한남2호점", PlaceType.CAFE),
    CuratedPlaceConfig("지엠엘 gml 한남", PlaceType.CAFE),
    CuratedPlaceConfig("릴리언 한남", PlaceType.CAFE),
    CuratedPlaceConfig("카프온카우치 한남", PlaceType.CAFE),
    CuratedPlaceConfig("블루보틀 한남", PlaceType.CAFE),
    CuratedPlaceConfig("타르틴베이커리 한남점", PlaceType.CAFE),
    CuratedPlaceConfig("댄스댄스댄스 한남", PlaceType.CAFE),
    CuratedPlaceConfig("피어커피바 한남", PlaceType.CAFE),
    CuratedPlaceConfig("에스프레소 코어 한남", PlaceType.CAFE),
    CuratedPlaceConfig("리카바이파프리카 한남", PlaceType.CAFE),
    CuratedPlaceConfig("mtl 한남", PlaceType.CAFE),
    CuratedPlaceConfig("마더오프라인 한남", PlaceType.CAFE),
    CuratedPlaceConfig("낫배드커피 한남", PlaceType.CAFE),
    CuratedPlaceConfig("한남작업실", PlaceType.CAFE),
    CuratedPlaceConfig("타르틴베이커리 이태원점", PlaceType.CAFE),
    CuratedPlaceConfig("하우스오브와일드 한남", PlaceType.CAFE),
    CuratedPlaceConfig("소브 한남", PlaceType.CAFE),
    CuratedPlaceConfig("세르클 한남", PlaceType.CAFE),
    CuratedPlaceConfig("사유 한남", PlaceType.CAFE),
    CuratedPlaceConfig("아우프글렛 한남점", PlaceType.CAFE),
    # Activity - 쇼핑 (SHOPPING)
    CuratedPlaceConfig("스컬프스토어 한남", PlaceType.ACTIVITY, ActivityKind.SHOPPING),
    CuratedPlaceConfig("비샵 한남 플래그십스토어", PlaceType.ACTIVITY, ActivityKind.SHOPPING),
    CuratedPlaceConfig("비이커 한남점", PlaceType.ACTIVITY, ActivityKind.SHOPPING),
    CuratedPlaceConfig("TW레코즈 한남", PlaceType.ACTIVITY, ActivityKind.SHOPPING),
    # Activity - 전시/문화 (EXHIBITION)
    CuratedPlaceConfig("현대카드 바이닐앤플라스틱", PlaceType.ACTIVITY, ActivityKind.EXHIBITION),
    CuratedPlaceConfig("리움미술관", PlaceType.ACTIVITY, ActivityKind.EXHIBITION),
    CuratedPlaceConfig("페이스갤러리 한남", PlaceType.ACTIVITY, ActivityKind.EXHIBITION),
    # Activity - 술집/이자카야/호프 (BAR, NIGHTLIFE)
    CuratedPlaceConfig("아쿠아 한남동", PlaceType.ACTIVITY, ActivityKind.BAR),
    CuratedPlaceConfig("서울집시 한남점", PlaceType.ACTIVITY, ActivityKind.BAR),
    CuratedPlaceConfig("방울과꼬막 한남", PlaceType.ACTIVITY, ActivityKind.BAR),
    CuratedPlaceConfig("서울에 살기 위하여 한남", PlaceType.ACTIVITY, ActivityKind.BAR),
    CuratedPlaceConfig("타키 한남점", PlaceType.ACTIVITY, ActivityKind.BAR),
    CuratedPlaceConfig("와 서울 와인바", PlaceType.ACTIVITY, ActivityKind.BAR),
    CuratedPlaceConfig("배반낭자 한남", PlaceType.ACTIVITY, ActivityKind.BAR),
    CuratedPlaceConfig("pave 와인바 한남", PlaceType.ACTIVITY, ActivityKind.BAR),
]

_YEONNAM_PLACES: List[CuratedPlaceConfig] = [
    # 레스토랑
    CuratedPlaceConfig("연교 연남", PlaceType.RESTAURANT),
    CuratedPlaceConfig("히사시돈부리 연남", PlaceType.RESTAURANT),
    CuratedPlaceConfig("숲길정육점 연남", PlaceType.RESTAURANT),
    CuratedPlaceConfig("야키토리묵 연남", PlaceType.RESTAURANT),
    CuratedPlaceConfig("랫댓 연남", PlaceType.RESTAURANT),
    CuratedPlaceConfig("우와 연남", PlaceType.RESTAURANT),
    CuratedPlaceConfig("바다약방 연남", PlaceType.RESTAURANT),
    CuratedPlaceConfig("연주방 연남", PlaceType.RESTAURANT),
    CuratedPlaceConfig("요코쵸 연남", PlaceType.RESTAURANT),
    CuratedPlaceConfig("이노시시 연남", PlaceType.RESTAURANT),
    CuratedPlaceConfig("스시지현 연남", PlaceType.RESTAURANT),
    CuratedPlaceConfig("연남닭발", PlaceType.RESTAURANT),
    CuratedPlaceConfig("용뱅이 연남", PlaceType.RESTAURANT),
    CuratedPlaceConfig("소이연남", PlaceType.RESTAURANT),
    CuratedPlaceConfig("화설 연남", PlaceType.RESTAURANT),
    CuratedPlaceConfig("연남면관", PlaceType.RESTAURANT),
    CuratedPlaceConfig("헤비스테이크 연남", PlaceType.RESTAURANT),
    CuratedPlaceConfig("백식당 연남", PlaceType.RESTAURANT, latitude=37.561833, longitude=126.925405),
    CuratedPlaceConfig("청화접 연남", PlaceType.RESTAURANT, latitude=37.563400, longitude=126.925634),
    CuratedPlaceConfig("요미우돈교자 연남점", PlaceType.RESTAURANT),
    CuratedPlaceConfig("초이다이닝 연남", PlaceType.RESTAURANT),
    # 카페
    CuratedPlaceConfig("수쿤 연남", PlaceType.CAFE),
    CuratedPlaceConfig("짙은산 연남", PlaceType.CAFE),
    CuratedPlaceConfig("코리코카페 연남", PlaceType.CAFE),
    CuratedPlaceConfig("메리트리 연남", PlaceType.CAFE),
    CuratedPlaceConfig("루치펠 연남", PlaceType.CAFE),
    CuratedPlaceConfig("조앤도슨 연남", PlaceType.CAFE),
    CuratedPlaceConfig("마사비스 연남", PlaceType.CAFE),
    CuratedPlaceConfig("앤티크커피 연남", PlaceType.CAFE),
    CuratedPlaceConfig("터틀힙 연남", PlaceType.CAFE),
    CuratedPlaceConfig("버터앤쉘터 연남", PlaceType.CAFE),
    CuratedPlaceConfig("유키모찌 연남", PlaceType.CAFE),
    CuratedPlaceConfig("팽페르뒤 연남", PlaceType.CAFE),
    CuratedPlaceConfig("치플레 연남", PlaceType.CAFE),
    CuratedPlaceConfig("에브리데이해피벌스데이 연남", PlaceType.CAFE),
    CuratedPlaceConfig("카페 오르트 연남", PlaceType.CAFE),
    CuratedPlaceConfig("레인리포트 브리티시 연남", PlaceType.CAFE, latitude=37.565314, longitude=126.924412),
    CuratedPlaceConfig("코코로카라 연남", PlaceType.CAFE),
    CuratedPlaceConfig("피프에스프레소바 연남", PlaceType.CAFE),
    CuratedPlaceConfig("몰리하우스 연남", PlaceType.CAFE),
    # Activity - 쇼핑 (SHOPPING)
    CuratedPlaceConfig("흑심 연남", PlaceType.ACTIVITY, ActivityKind.SHOPPING),
    CuratedPlaceConfig("어쩌다 책방 연남", PlaceType.ACTIVITY, ActivityKind.SHOPPING),
    CuratedPlaceConfig("해리스플라워마켓 연남", PlaceType.ACTIVITY, ActivityKind.SHOPPING),
    CuratedPlaceConfig("고양이가있는액자가게 연남", PlaceType.ACTIVITY, ActivityKind.SHOPPING),
    CuratedPlaceConfig("글리밍데이 연남", PlaceType.ACTIVITY, ActivityKind.SHOPPING),
    CuratedPlaceConfig("메이드바이 연남", PlaceType.ACTIVITY, ActivityKind.SHOPPING),
    CuratedPlaceConfig("챔토피아 연남", PlaceType.ACTIVITY, ActivityKind.SHOPPING),
    CuratedPlaceConfig("보라앤드 연남소품샵", PlaceType.ACTIVITY, ActivityKind.SHOPPING, latitude=37.563165, longitude=126.925504),
    # Activity - 체험 (WORKSHOP)
    CuratedPlaceConfig("도토리캐리커쳐 연남", PlaceType.ACTIVITY, ActivityKind.WORKSHOP),
    CuratedPlaceConfig("더필름 연남", PlaceType.ACTIVITY, ActivityKind.WORKSHOP),
    CuratedPlaceConfig("무인공방 연남", PlaceType.ACTIVITY, ActivityKind.WORKSHOP),
    CuratedPlaceConfig("타다도자기공방 연남", PlaceType.ACTIVITY, ActivityKind.WORKSHOP, latitude=37.563750, longitude=126.926788),
    CuratedPlaceConfig("뤼미에르퍼퓸 연남", PlaceType.ACTIVITY, ActivityKind.WORKSHOP),
    CuratedPlaceConfig("밀실 연남", PlaceType.ACTIVITY, ActivityKind.WORKSHOP),
    CuratedPlaceConfig("칠앤아트 연남", PlaceType.ACTIVITY, ActivityKind.WORKSHOP),
    CuratedPlaceConfig("아이아이연남", PlaceType.ACTIVITY, ActivityKind.WORKSHOP),
    # Activity - 실내놀이 (INDOOR_PLAY)
    CuratedPlaceConfig("점핑배틀 연남", PlaceType.ACTIVITY, ActivityKind.INDOOR_PLAY),
    CuratedPlaceConfig("비트포비아 연남", PlaceType.ACTIVITY, ActivityKind.INDOOR_PLAY, latitude=37.549644, longitude=126.917371),
]

_YEONHUI_PLACES: List[CuratedPlaceConfig] = [
    # 레스토랑
    CuratedPlaceConfig("홍대 삭 연희", PlaceType.RESTAURANT, latitude=37.566350, longitude=126.930219),
    CuratedPlaceConfig("목란 연희", PlaceType.RESTAURANT),
    CuratedPlaceConfig("연희동 칼국수", PlaceType.RESTAURANT, latitude=37.568324, longitude=126.930755),
    CuratedPlaceConfig("오향만두 연희", PlaceType.RESTAURANT),
    CuratedPlaceConfig("우동카덴 연희", PlaceType.RESTAURANT),
    CuratedPlaceConfig("오트 연희", PlaceType.RESTAURANT),
    CuratedPlaceConfig("링키지버거 연희", PlaceType.RESTAURANT),
    CuratedPlaceConfig("쿳사연희", PlaceType.RESTAURANT),
    CuratedPlaceConfig("니바하우스 연희", PlaceType.RESTAURANT),
    CuratedPlaceConfig("그로어스 연희", PlaceType.RESTAURANT),
    CuratedPlaceConfig("그레인서울 연희", PlaceType.RESTAURANT),
    CuratedPlaceConfig("타라이 연희", PlaceType.RESTAURANT),
    CuratedPlaceConfig("장작새 연남", PlaceType.RESTAURANT, latitude=37.564274, longitude=126.926211),
    CuratedPlaceConfig("도우클럽 연희", PlaceType.RESTAURANT),
    CuratedPlaceConfig("시오 연희본점", PlaceType.RESTAURANT),
    CuratedPlaceConfig("마우디 연희", PlaceType.RESTAURANT),
    CuratedPlaceConfig("원순철판동태찜 연희", PlaceType.RESTAURANT, latitude=37.567213, longitude=126.929076),
    CuratedPlaceConfig("이화원 연희", PlaceType.RESTAURANT),
    CuratedPlaceConfig("청송함흥냉면전문점 본관", PlaceType.RESTAURANT),
    CuratedPlaceConfig("리정원 연희", PlaceType.RESTAURANT),
    CuratedPlaceConfig("난포 한남", PlaceType.RESTAURANT),
    # 카페
    CuratedPlaceConfig("킷사카라수 연희", PlaceType.CAFE),
    CuratedPlaceConfig("데스툴 연희", PlaceType.CAFE),
    CuratedPlaceConfig("프로토콜 연희점", PlaceType.CAFE),
    CuratedPlaceConfig("디파트먼트이엔 연희", PlaceType.CAFE),
    CuratedPlaceConfig("새라울 연희", PlaceType.CAFE),
    CuratedPlaceConfig("매뉴팩트커피 연희본점", PlaceType.CAFE),
    CuratedPlaceConfig("연희 에스프레소바", PlaceType.CAFE),
    CuratedPlaceConfig("에브리띵베이글 연희", PlaceType.CAFE),
    CuratedPlaceConfig("스웨이커피스테이션 연희", PlaceType.CAFE),
    CuratedPlaceConfig("센티멘트 연희", PlaceType.CAFE),
    CuratedPlaceConfig("동경책방 연희", PlaceType.CAFE),
    CuratedPlaceConfig("목화씨라운지 연희", PlaceType.CAFE),
    CuratedPlaceConfig("더니커피 연희", PlaceType.CAFE),
    CuratedPlaceConfig("로도덴드론 연희 3호점", PlaceType.CAFE, latitude=37.568611, longitude=126.929659),
    # Activity - 쇼핑 (SHOPPING)
    CuratedPlaceConfig("글월 연희", PlaceType.ACTIVITY, ActivityKind.SHOPPING),
    CuratedPlaceConfig("빅슬립 연희", PlaceType.ACTIVITY, ActivityKind.SHOPPING),
    CuratedPlaceConfig("카키스 연희", PlaceType.ACTIVITY, ActivityKind.SHOPPING),
    CuratedPlaceConfig("유어마인드 연희", PlaceType.ACTIVITY, ActivityKind.SHOPPING),
    CuratedPlaceConfig("그린디자인웍스 공장 연희", PlaceType.ACTIVITY, ActivityKind.SHOPPING),
    CuratedPlaceConfig("티티에이 연희", PlaceType.ACTIVITY, ActivityKind.SHOPPING),
    CuratedPlaceConfig("포셋 연희", PlaceType.ACTIVITY, ActivityKind.SHOPPING),
    CuratedPlaceConfig("사러가 연희", PlaceType.ACTIVITY, ActivityKind.SHOPPING),
    CuratedPlaceConfig("현대카드 뮤직 라이브러리", PlaceType.ACTIVITY, ActivityKind.SHOPPING),
    # Activity - 체험 (WORKSHOP)
    CuratedPlaceConfig("옵젵상가 연희", PlaceType.ACTIVITY, ActivityKind.WORKSHOP),
    # Activity - 전시/문화 (EXHIBITION)
    CuratedPlaceConfig("라이카시네마 연희", PlaceType.ACTIVITY, ActivityKind.EXHIBITION),
    # Activity - 칵테일바/와인바/이자카야 (BAR)
    CuratedPlaceConfig("희로 연희", PlaceType.ACTIVITY, ActivityKind.BAR),
    CuratedPlaceConfig("정키 연희", PlaceType.ACTIVITY, ActivityKind.BAR),
]

_CURATED_BY_AREA: Dict[str, List[CuratedPlaceConfig]] = {
    "성수": _SEONGSU_PLACES,
    "성수동": _SEONGSU_PLACES,
    "성수역": _SEONGSU_PLACES,
    "한남": _HANNAM_PLACES,
    "한남동": _HANNAM_PLACES,
    "연남": _YEONNAM_PLACES,
    "연남동": _YEONNAM_PLACES,
    "연남역": _YEONNAM_PLACES,
    "연희": _YEONHUI_PLACES,
    "연희동": _YEONHUI_PLACES,
}


def get_curated_configs(area: str) -> List[CuratedPlaceConfig]:
    return _CURATED_BY_AREA.get(area.strip(), [])
